services:
  web:
    build: .
    command: sh -c "python server/manage.py makemigrations &&
                    python server/manage.py migrate &&
                    python server/db_init.py &&
                    python server/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
    - POSTGRES_PASSWORD=${PASS_KEY}
    - POSTGRES_DB=prankgptdb
    - POSTGRES_USER=postgres
    ports:
      - "5376:5432"
