# Generated by Django 4.1.5 on 2023-01-11 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('views', models.IntegerField()),
                ('replies', models.IntegerField()),
                ('blink', models.SlugField(max_length=255)),
            ],
            options={
                'db_table': 'creator',
                'ordering': ['-views'],
            },
        ),
        migrations.CreateModel(
            name='Rentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkpage.creator')),
            ],
            options={
                'db_table': 'rentry',
            },
        ),
    ]
