# Generated by Django 4.1.4 on 2023-01-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='slug',
        ),
    ]
