# Generated by Django 4.1.4 on 2023-01-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkpage', '0002_remove_creator_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={'ordering': ['views']},
        ),
        migrations.AlterField(
            model_name='creator',
            name='replies',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creator',
            name='views',
            field=models.IntegerField(),
        ),
    ]
