# Generated by Django 4.1.4 on 2023-01-02 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkpage', '0003_alter_creator_options_alter_creator_replies_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={'ordering': ['-views']},
        ),
    ]
